name = "kernel"
kind = "exe"
output = "jsix.elf"
targets = ["kernel"]
deps = ["kutil", "cpu"]
includes = ["src/kernel"]
sources = [
    "apic.cpp",
    "ap_startup.s",
    "boot.s",
    "clock.cpp",
    "console.cpp",
    "cpprt.cpp",
    "cpu.cpp",
    "debug.cpp",
    "debug.s",
    "device_manager.cpp",
    "frame_allocator.cpp",
    "gdt.cpp",
    "gdtidt.s",
    "hpet.cpp",
    "idt.cpp",
    "interrupts.cpp",
    "interrupts.s",
    "io.cpp",
    "log.cpp",
    "main.cpp",
    "memory_bootstrap.cpp",
    "msr.cpp",
    "objects/channel.cpp",
    "objects/endpoint.cpp",
    "objects/kobject.cpp",
    "objects/thread.cpp",
    "objects/process.cpp",
    "objects/system.cpp",
    "objects/vm_area.cpp",
    "page_table.cpp",
    "page_tree.cpp",
    "pci.cpp",
    "scheduler.cpp",
    "serial.cpp",
    "syscall.cpp",
    "syscall.s",
    "syscalls/channel.cpp",
    "syscalls/endpoint.cpp",
    "syscalls/object.cpp",
    "syscalls/process.cpp",
    "syscalls/system.cpp",
    "syscalls/thread.cpp",
    "syscalls/vm_area.cpp",
    "task.s",
    "tss.cpp",
    "vm_space.cpp",
]

[variables]
ldflags = ["${ldflags}", "-T", "${source_root}/src/kernel/kernel.ld"]
