name = "kutil"
kind = "lib"
includes = [ "src/libraries/kutil/include" ]
sources = [
    "assert.cpp",
    "bip_buffer.cpp",
    "heap_allocator.cpp",
    "logger.cpp",
    "memory.cpp",
    "printf.c",
    "spinlock.cpp",
]
