---
extends: base

variables:
  asflags: [ "-I${source_root}/src/kernel/" ]

  ccflags: [
    "--target=x86_64-unknown-elf",
    "-I${source_root}/external",

    "-nostdlib",
    "-ffreestanding",
    "-nodefaultlibs",
    "-fno-builtin",

    "-mno-sse",
    "-fno-omit-frame-pointer",
    "-mno-red-zone",
    "-mcmodel=large",

    "-g",

    "-D__ELF__",
    "-D__JSIX__",
    "-U__linux",
    "-U__linux__",

    "-isystem${source_root}/sysroot/include",
    "-isystem${source_root}/src/libraries/libc/include",
    "--sysroot='${source_root}/sysroot'" ]


  cflags: [ '-nostdinc' ]

  cxxflags: [
    "-fno-exceptions",
    "-fno-rtti",
    "-nostdinc",
    "-isystem${source_root}/sysroot/include/c++/v1" ]

  ldflags: [
    "-g",
    "-nostdlib",
    "-Bstatic",
    "-z", "norelro",
    "-z", "separate-code" ]

