---
extends: base

variables:
  asflags: [ "-I${source_root}/src/kernel/" ]

  ccflags: [
    "-mno-sse",
    "-fno-omit-frame-pointer",

    "-g",

    "-D__ELF__",
    "-D__jsix__",
    "-U__linux",
    "-U__linux__",

    "-isystem${source_root}/sysroot/include",
    "-isystem${build_root}/include/libc",
    "--sysroot='${source_root}/sysroot'" ]


  cxxflags: [
    "-fno-exceptions",
    "-fno-rtti",
    "-isystem${source_root}/sysroot/include/c++/v1" ]

  ldflags: [
    "-g",
    "-Bstatic",
    "--sysroot='${source_root}/sysroot'",
    "-L", "${source_root}/sysroot/lib",
    "-z", "separate-code" ]

